version: '3'

services:

  postgres-db:
    image: postgres:15.3
    container_name: local-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: events-db
    networks:
      - api-events
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile

    volumes:
      - .:/app/
      - /app/node_modules
    restart: always
    container_name: api-events-container
    ports:
      - ${PORT}:${PORT}
    networks:
      - api-events
    depends_on:
      - postgres-db
    environment:
      PORT: ${PORT}
      DATABASE_NAME: events-db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_HOST: postgres-db
      DATABASE_PORT: 5432
      SECRET_OR_PRIVATE_KEY: esteEsmiSecretKey
      MAPBOX_ACCESS_TOKEN: ${MAPBOX_ACCESS_TOKEN}
networks:
  api-events:
    driver: bridge
